spring.application.name=notification-ses-service


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Database Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/notification_service
spring.datasource.username=notification_user
spring.datasource.password=Not!fi!c@t!on1
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Optional: Connection Pool Settings (HikariCP is default)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# JPA (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

#aws.accessKeyId=AKIATCKAQLOUOPHTOIDF1
#aws.secretAccessKey=P6XzuU1f6BJkICk97wF11pMTHS60/c5o3BK2ogMI1
#aws.region=ap-south-1
#aws.sqslUrl=https://sqs.ap-south-1.amazonaws.com/211125558184/sqs-notifications

aws.accessKeyId=AKIAS55DKDVPDDWPKAKJ1
aws.secretAccessKey=5INqCSWsRkmZIIFCFCZPibZX06lXzH9aG1Nsl8ER1
aws.region=us-east-1
aws.sqslUrl=https://sqs.us-east-1.amazonaws.com/201669090654/email_notification_queue
activemq.mailboxQ=mailboxQ
activemq.messageIdQ=messageIdQ


