spring.application.name=notification-ses-service


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Database Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/notification_service
spring.datasource.username=notification_user
spring.datasource.password=Not!fi!c@t!on
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Optional: Connection Pool Settings (HikariCP is default)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# JPA (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin


#Sunil
aws.accessKeyId=XXXXXXXXX
aws.secretAccessKey=XXXXXXXX
aws.region=ap-south-1
aws.sqslUrl=https://sqs.ap-south-1.amazonaws.com/211125558/sqs-notifications

activemq.mailboxQ=mailboxQ
activemq.messageIdQ=messageIdQ



#Logging : Only the INFO, WARN, and ERROR logs will appear, if you want to print the debug logs then comment below configuration
logging.level.root=INFO

# The delay in milliseconds after processing a message from the mailbox queue.
app.jms.listener.delay-ms=250


# Custom application properties
notification.job.chunk-size=100

# Scheduler timings in milliseconds
# How long to wait between the end of one execution and the start of the next
notification.job.fixed-delay=12000

# How long to wait before the first execution after application startup
notification.job.initial-delay=6000


# Query to populate the initial message ID lookup table.
# This query is safe to re-run thanks to `INSERT IGNORE`.
maintenance-job.queries.aggregate-initial-messages=INSERT IGNORE INTO notification_initial_message_id (sender_email, recipient_email, message_id) \
SELECT sender_email, recipient_email, ses_message_id \
FROM ( \
    SELECT sender_email, recipient_email, ses_message_id, \
           ROW_NUMBER() OVER(PARTITION BY sender_email, recipient_email ORDER BY sent_timestamp ASC) as rn \
    FROM notification \
    WHERE ses_message_id IS NOT NULL \
) as ranked_notifications \
WHERE rn = 1

# Query for moving records to the history table.
maintenance-job.queries.archive-notifications=INSERT INTO notification_history SELECT * FROM notification WHERE date(created_at) < subdate(now(), 10) AND status IS NOT NULL AND status NOT IN ('PENDING')

# Query for deleting the archived records from the main notification table.
maintenance-job.queries.delete-archived-notifications=DELETE FROM notification WHERE date(created_at) < subdate(now(), 10) AND status IS NOT NULL AND status NOT IN ('PENDING')
# Cron expression for scheduling the maintenance job (every day at 2 AM).
maintenance-job.cron=0 */5 * * * *
