spring.application.name=notification-ses-service


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Database Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/notification_service
spring.datasource.username=notification
spring.datasource.password=Dummypassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Optional: Connection Pool Settings (HikariCP is default)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# JPA (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

aws.accessKeyId=XXXXXXXXXX
aws.secretAccessKey=YYYYYYYYYYY
aws.region=us-east-1
aws.sqslUrl=https://sqs.us-east-1.amazonaws.com/queue
activemq.mailboxQ=mailboxQ
activemq.messageIdQ=messageIdQ



#Logging : Only the INFO, WARN, and ERROR logs will appear, if you want to print the debug logs then comment below configuration
logging.level.root=INFO
